version: "3.7"
services:
  buildtagpush:
    build: .
    image: mattipaksula/buildtagpush:latest
    environment:
      - REGISTRY=mattipaksula
      - IMAGE=buildtagpush
      - TAG=edge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace
  trypull:
    build: .
    image: mattipaksula/buildtagpush:latest
    command:
      - trypull
      - notexist:notlatest
      - alpine:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
